package me.yeoc.educlient.object;

import lombok.Data;

@Data
public class CourseQueryContext {
    private String rwlx;
    private String kczxskg;
    private String kklxpx;
    private String xklc;
    private String xklcmc;
    private String bklxId;
    private String zckz;
    private String sfzyxk;
    private String sfyjxk;
    private String zdzys;
    private String sfqzxk;
    private String sfkknj;
    private String knjkxdnj;
    private String sfkkzy;
    private String kzybkxy;
    private String sfznkx;
    private String zdkxms;
    private String sfkxq;
    private String sfkcfx;
    private String kkbk;
    private String kkbkdj;
    private String sfkxk;
    private String sfktk;
    private String txbsfrl;
    private String tktjrs;
    private String rlzlkz;
    private String cdrllkz;
    private String rlkz;
    private String xkly;
    private String sfyxsksjct;
    private String ddkzbj;
    private String cxddkzbj;
    private String sfkkjyxdxnxq;
    private String sfkgbcx;
    private String xkxskcgskg;
    private String tkzgcsJb;
    private String jxbzcxskg;
    private String xkzgbj;
    private String sfrxtgkcxd;
    private String tykczgxdcs;
    private String sxrlkzlx;
    private String isinxksj;
    private String xksjxskz;
    private String lnzkcs;
    private String lnzxfs;
    private String bxqzdxkxf;
    private String bxqzgxkxf;
    private String bxqzdxkmc;
    private String bxqzgxkmc;
    private String lnzdxkxf;
    private String lnzgxkxf;
    private String lnzdyhxf;
    private String lnzgyhxf;
    private String lnzdxkmc;
    private String lnzgxkmc;
    private String bbhzxjxb;
    private String syts;
    private String syxs;
    private String jdlx;
    private String bjgkczxbbjwcx;
    private String jspage;
    private String xkydjc;
    private String lnzgxkxs;
    private String bxqzgxkxs;
    private String kzkcgs;
    private String globJsPage;
    private String jsKcrow;
    private String isEnd;
}
